[package]
name = "bgm-macros"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Procedural macros for BGM (derive(Interpolate))"

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
