[package]
name = "bgm-protocols"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "BGM protocol strategies: HttpProtocol over reqwest"

[lints]
workspace = true

[dependencies]
bgm-core.workspace = true
bgm-scenario.workspace = true
async-trait.workspace = true
reqwest.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-tungstenite.workspace = true
futures-util.workspace = true
